### ISSUE TITLE
Error using the DS3232 library; no matching function for call to 'DS3232RTC::DS3232RTC(SoftI2C&)'

### ISSUE THREAD

**Issue by pssen** [rweather/arduinolibs#14]
I  am a newbie to the Arduino.  I have connected the DS3232 RTC clock module to the Arduino Uno and have tried to upload the sketch -TestRTC from File ->Examples ->RTC ->TestRTC.  but receive the error, " Not used: C:\Users\Paul\Documents\Arduino\libraries\RTC
exit status 1
no matching function for call to 'DS3232RTC::DS3232RTC(SoftI2C&)'"

![image](https://cloud.githubusercontent.com/assets/24249109/20711432/b44617f4-b650-11e6-8e00-cee469946373.png)

I followed the instructions listed here http://www.freetronics.com.au/pages/rtc-real-time-clock-module-quickstart-guide#.WDyUaPl96yI.

My IDE is Arduino v. 1.6.9

I have tried without success to look for the cause of the error. Kindly help.

I look forward to hearing from you

**Comment by rweather** [comment]
The non-crypto stuff including the RTC code has been moved to a separate repository:

https://github.com/rweather/arduino-projects

If you are still having problems, please open a new issue on that repository.  

Sorry I didn't get to this earlier.  I just noticed in the screenshot that it shows "Not used: C:\Users\Paul\Documents\Arduino\libraries\RTC".  Possibly you have some other RTC library installed elsewhere and there are conflicts.
