### ISSUE TITLE
ECDH not using private key as input

### ISSUE THREAD

**Issue by onlykey** [rweather/arduinolibs#16]
Hi,

Great job on this project it is top notch. I am using a modified version of the RNG, AES-GCM, and Ed25519 for our OnlyKey firmware.

I am implementing ECDH now and I am wondering if I am missing something here. You have DH1 and DH2 functions but neither uses the private key as an input, just public key. https://rweather.github.io/arduinolibs/classCurve25519.html

The other implementations I have seen use a private and public key to generate the shared secret - Mbedtls for example. I have to be missing something here because using public keys from each party to generate shared secret would mean that anyone with access to the public keys would be able to generate the shared secret too and decrypt communication.

Thanks,

**Comment by rweather** [comment]
The dh1() and dh2() functions are for convenience in a two-party exchange.  The dh1() function generates the local party's private key internally and returns it as the "f" parameter.  The public key is returned in the "k" parameter.  Once the other party's "k" has been received, call dh2() to complete the exchange to generate the shared secret.

Effectively dh1() is "generate keypair" and dh2() is "generate shared secret from remote public key k and local private key f".

If you need more control over the process, then eval() can be used instead.  That function is closer to the traditional curve operation that you see in other libraries.
