### ISSUE TITLE
EEPROM24 libs modify

### ISSUE THREAD

**Issue by roriB88** [rweather/arduinolibs#17]
Hi, I have used for some time the library EEPROM24 with excellent results. I have a request: how can I change it to hide the ACK EPROM?
I would write the EPROM without waiting for its answer. 
You can show me how to make the change?
Thank you

**Comment by rweather** [comment]
I'm not sure what problem you are trying to solve here.  Are you trying to perform the I2C requests in the background while you do other tasks in the foreground?  That would require interrupt-driven I2C which my API doesn't currently support.
