### ISSUE TITLE
TransistorNoiseSource.h is missing from package

### ISSUE THREAD

**Issue by ciband** [rweather/arduinolibs#29]
The TransistorNoiseSource.h header is missing from the plaformio package, or the seperate TransistorNoiseSource library is not published to plaformio.

**Comment by rweather** [comment]
I have added library.json files to all library directories.  However, since I don't use PlatformIO myself I don't know how to "publish" the libraries any further than that, or even how to test if I have created the library.json files correctly for the PlatformIO framework.
