### ISSUE TITLE
RNG Compilation on STM32L073RZ

### ISSUE THREAD

**Issue by n9wxu** [rweather/arduinolibs#56]
The STM32L073RZ has a HW RNG with the unfortunate register name of RNG.
This collides with the RNGClass RNG; line on RNG.cpp:159

The RNG global needs a new name.

I suffixed RNG with _ making RNG_ for a temporary hack.  Fortunately I do not need the RNG at this time.

**Comment by rweather** [comment]
You may also be able to work around the issue by putting "#undef RNG" in various places to remove the definition that comes from the system headers.  And then later redefine "RNG_SYSTEM" to the underlying register pointer to use the system random number source as a TRNG.
