### ISSUE TITLE
’SHA256‘  was not declared in this scope ESP32S3

### ISSUE THREAD

**Issue by KINGJ7** [rweather/arduinolibs#78]
Hi, I've been using #include<SHA256.h> #<Crypto.h> on Arduino ide2.0.4 with my ESP32S3,
 Error compiling for board ESP32S3（2.0.7）version

【/Users/king.j1/Documents/Arduino/libraries/YYZT_AliyunMqtt/src/YYZT_AliyunMqtt.cpp: In member function 'String AliyunMqtt::hmac256(const String&, const String&)':
/Users/king.j1/Documents/Arduino/libraries/YYZT_AliyunMqtt/src/YYZT_AliyunMqtt.cpp:295:3: error: 'sha256' was not declared in this scope
   sha256.resetHMAC(key, keySize);
   ^~~~~~
/Users/king.j1/Documents/Arduino/libraries/YYZT_AliyunMqtt/src/YYZT_AliyunMqtt.cpp:295:3: note: suggested alternative: 'hmac256'
   sha256.resetHMAC(key, keySize);
   ^~~~~~
   hmac256】

How to solve this problem？Thanks

**Comment by rweather** [comment]
I suspect that there is a conflict with the headers in the toolchain for the ESP32S3.  Maybe it has its own version of Crypto.h or SHA256.h and that header is getting picked up instead.  It wouldn't be the first time that the system headers for ESP32 have conflicted in this way.  I'm not really sure how to force a sketch to use the headers in my library instead of the system headers.  You may want to also talk to the authors of AliyunMqtt to see if they have a solution.

**Comment by KINGJ7** [comment]
> I suspect that there is a conflict with the headers in the toolchain for the ESP32S3. Maybe it has its own version of Crypto.h or SHA256.h and that header is getting picked up instead. It wouldn't be the first time that the system headers for ESP32 have conflicted in this way. I'm not really sure how to force a sketch to use the headers in my library instead of the system headers. You may want to also talk to the authors of AliyunMqtt to see if they have a solution.

I also get this error using the SHA256.io and the header of SHA256.h ， in your Crypto library‘s example

**Comment by KINGJ7** [comment]
> I suspect that there is a conflict with the headers in the toolchain for the ESP32S3. Maybe it has its own version of Crypto.h or SHA256.h and that header is getting picked up instead. It wouldn't be the first time that the system headers for ESP32 have conflicted in this way. I'm not really sure how to force a sketch to use the headers in my library instead of the system headers. You may want to also talk to the authors of AliyunMqtt to see if they have a solution.

I have no problem using other libraries, such as SHA224.h and SHA384.h and so on，The problem seems to be unique to the SHA256.h ，If you know how to solve it, please let me know，thanks

**Comment by rweather** [comment]
It looks like your ESP toolchain has both Crypto.h and SHA256.h headers, which are conflicting with the ones in my library.  Here are some options:

- Rename the files in my library to something else like CryptoA.h and SHA256A.h or something.  And then change anything that refers to them.
- Rename the headers in the toolchain itself.
- Find some way to modify the Arduino IDE's or the toolchain's include path to put my library first in the path.

Sorry I cannot be much more help than that.

**Comment by KINGJ7** [comment]
> It looks like your ESP toolchain has both Crypto.h and SHA256.h headers, which are conflicting with the ones in my library. Here are some options:
> 
> * Rename the files in my library to something else like CryptoA.h and SHA256A.h or something.  And then change anything that refers to them.
> * Rename the headers in the toolchain itself.
> * Find some way to modify the Arduino IDE's or the toolchain's include path to put my library first in the path.
> 
> Sorry I cannot be much more help than that.

Thanks bro，I have solved the problem^_^

**Comment by rweather** [comment]
For my curiosity and the benefit of others with the same problem, how did you end up solving the problem?
